version: '3'

services:
    nginx:
        build: /home/ylazrek/Desktop/inception/srcs/requirements/nginx
        image: nginx
        container_name: nginx
        ports:
            - "443:443"
        volumes:
            - wp_file_data:/var/www
        networks:
            - inception_net
        restart: always
    mariadb:
        build: /home/ylazrek/Desktop/inception/srcs/requirements/mariadb
        image: mariadb
        container_name: mariadb
        env_file:
            - .env
        volumes:
            - wp_DB_data:/var/lib/mysql
        networks:
            - inception_net
        restart: always
    wordpress:
        build: /home/ylazrek/Desktop/inception/srcs/requirements/wordpress
        image: wordpress
        container_name: wordpress
        env_file:
            - .env
        volumes:
            - wp_file_data:/var/www
        networks:
            - inception_net
        depends_on:
            - nginx
            - mariadb
        restart: always


volumes:
    wp_file_data:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/ylazrek/data/wp_file_data'
    wp_DB_data:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/ylazrek/data/wp_DB_data'

networks:
    inception_net:
        name: "inception_net"